### ISSUE TITLE
superbuild fails when building icu [Windows 7 x64, Visual Studio 2015]  

### ISSUE THREAD

**Issue by seanwarren** [ome/ome-cmake-superbuild#164]
Hello, 

Compiling the super-build on windows 7 with visual studio 2015 fails with the following output while building `icu`

```
"C:\Users\CIMLab\Documents\flim-ui\ome-files-build\install.vcxproj" (default target) (1) ->
"C:\Users\CIMLab\Documents\flim-ui\ome-files-build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\CIMLab\Documents\flim-ui\ome-files-build\icu.vcxproj" (default target) (6) ->
(CustomBuild target) ->
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1098,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, instal
l the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from
the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\CIMLab\Documents\flim-ui\ome-files-b
uild\icu-source\source\data\makedata.vcxproj] [C:\Users\CIMLab\Documents\flim-ui\ome-files-build\icu.vcxproj]
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1098,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, instal
l the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from
the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\CIMLab\Documents\flim-ui\ome-files-b
uild\icu-source\source\data\makedata.vcxproj] [C:\Users\CIMLab\Documents\flim-ui\ome-files-build\icu.vcxproj]

    6474 Warning(s)
    2 Error(s)
```

.NET framework v4 is installed. 

Thanks,
Sean

**Comment by rleigh-codelibre** [comment]
I think you need not only .NET v4, but the .NET v4 SDK which (if I recall correctly) is one of the optional visual studio components but I think it's installed by default. 
 https://stackoverflow.com/questions/44548780/the-reference-assemblies-for-framework-netframework-version-v4-6-2-were-not-f suggests that there are multiple bits of .NET which can be installed separately, so it might be that one or more of these extra bits are missing?

That said, on all our machines we use a stock VS2015 install with nothing but the C++ compiler installed on Windows 7 and Server 2012, and I've not seen this error to date.  Unless something changed very recently on Windows 7, and we simply haven't encountered it yet.  I am not a .NET expert by any means however, so there may be some subtlety I haven't understood.

I'd suggest checking if installing those missing bits helps in the first instance.

**Comment by rleigh-codelibre** [comment]
@seanwarren Did the above suggestion work, or is this still an ongoing problem?

Thanks,
Roger

**Comment by seanwarren** [comment]
Hi Roger, apologies for not getting back to you - shortly after I switched to using external llibraries provided by vcpkg/homebrew. However I seem to remember that this suggestion resolved the issue. 

Cheers
Sean
